[package]
name = "mandoline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
static_assertions = "1.1.0"
mandoline-stl = { path = "../stl" }
mandoline-mesh = { path = "../mesh" }
