[package]
name = "mandoline-stl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
byteorder = "1.4.3"
mandoline-mesh = { path = "../mesh" }

[dev-dependencies]
wasm-bindgen-test = "0.3.36"