name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
    - name: Install wasm32 toolchain
      run: |
        rustup target add wasm32-unknown-unknown
    - name: Install wasm-bindgen-cli
      uses: taiki-e/install-action@v2
      with:
        tool: wasm-bindgen-cli@0.2.86
    - name: Verify
      run: just run-ci
